conu/utils/probes.py

has also commits from `fix-ci` branch
```
Traceback (most recent call last):
File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/tt/.local/lib/python3.6/site-packages/conu/utils/probes.py", line 81, in _wrapper
% (self.fnc.__name__, str(self.kwargs), round(time.time() - start), self.timeout))
AttributeError: 'partialmethod' object has no attribute '__name__'
```

probe: some functions don't have names

---

conu/backend/docker/container.py
tests/unit/test_docker_container.py

Should also fix https://github.com/fedora-modularity/conu/issues/80
Needs to be rebased when https://github.com/fedora-modularity/conu/pull/85 is merged due to container.rm() in https://github.com/dhodovsk/conu/blob/59a0a09559dde285556802eb0d1cd1d256b538a4/tests/unit/test_docker_container.py

Add methods for checking mapped ports

---

MANIFEST.in
Makefile
conu.spec

* blocker: https://github.com/dgoodwin/tito/issues/308, removing tito for now

package conu as an RPM

---

docs/source/conf.py

When the package is not yet installed, this allow you to build the docs
without explicitly setting the PYTHONPATH.

Make the docs build against the project path

---

conu/backend/docker/backend.py
conu/backend/docker/constants.py
conu/backend/docker/container.py
conu/backend/docker/image.py
tests/integration/test_backend.py
tests/unit/test_docker_container.py

This PR implements following functionality:
- Label containers created with conu - in run_via_binary - should be also invoked in implementation of run_via_api
- Tag images pulled by conu - comes along with presence check of images before pulling
- when Prune is run, all containers with conu label and images with conu tag are removed

Cleanup methods for containers and images

---

docs/Makefile
docs/api_status/__init__.py
docs/source/conf.py

Let's merge #122 first.
This patch appends status of implementation of class' methods. This information is recorded in class' docstring; e.g.:
```
These methods are specific to this backend:
* `get_port_mappings`
* `wait_for_port`
* `inspect`
```

document implementation status of methods

---

conu.spec

I'm going to fix this in Fedora too, but I want upstream spec file to be the same, so I don't create some kind of mess. I don't think this warrants even a minor release, so I'm just gonna  bump up release number and keep version the same.
All this does is exclude `ppc64` architecture because of broken dependencies. You can refer to bugzilla link for more details.

Fix broken building in Fedora

---

README.md
conu/backend/docker/container.py
conu/backend/docker/image.py
docs/source/asciinema.rst
docs/source/examples/check_env.py
docs/source/examples/check_port.py
docs/source/examples/client-server-request.py
docs/source/examples/readme_webserver.py
docs/source/examples/run_image.py
docs/source/examples/webserver.py
tests/integration/test_backend.py
tests/integration/test_docker.py
tests/integration/test_filesystem.py
tests/integration/test_s2i.py
tests/release/test_release.py
tests/unit/test_docker_container.py

This PR changes the `.run_via_binary` to accept `command` and `additional_opts` as a list of strings. See #143. 
I will be glad for the reviews and comments.
This PR is WIP, after changes in code will be approved the docs and README needs to be updated also.

`run_via_binary` accept command as a list of strings

---

docs/source/installation.rst

[Problems with CentOS](https://github.com/fedora-modularity/conu/issues/106) were fixed on #130  and Conu works on CentOS since [release 0.2.0](https://github.com/fedora-modularity/conu/releases/tag/0.2.0) .

installation.rst update

---

conu/apidefs/backend.py
conu/apidefs/image.py
conu/backend/docker/backend.py
tests/integration/test_backend.py

Fix #162 and #163
- cleanup methods are now part of the stable API
- cleanup parameter now accepts list of `CleanupPolicy` enum values
I would be glad for the review and feedback.

Image cleanup policy upgrade

---

conu/backend/nspawn/container.py
conu/backend/nspawn/image.py
tests/integration/test_nspawn_backend.py

* add machined restart method, it sometimes hangs.
* renamed ``run`` to ``run_via_binary`` to be api compatible.
* add sleep after pull-raw to ensure that all file ops finished well.
* need to fix issue with failed starts

add machinectl service reset and renamed run -> run_via_binary, to be compatible with API

---

release-conf.yaml

to be able to release on PyPi & Fedora (no Bodhi support yet)
I guess we also need to add https://src.fedoraproject.org/user/usercont commit rights to https://src.fedoraproject.org/rpms/conu don't we ?
(you can add jpopelka too BTW)

Add configuration for release-bot

---

conu/backend/docker/image.py
tests/integration/data/greeter/Dockerfile
tests/integration/test_docker.py

Fixes: https://github.com/fedora-modularity/conu/issues/77
If you think another option from https://github.com/docker/docker-py/blob/master/docker/api/build.py#L60 should be added, please, let me know.

Add ability to build docker image from Dockerfile

---

README.md
conu.spec
conu/__init__.py
conu/backend/docker/container.py
conu/backend/docker/image.py
conu/utils/__init__.py
pytest-container.ini
requirements.sh
tests/integration/test_docker.py
tests/integration/test_filesystem.py
tests/integration/test_utils.py

which means, we no longer need atomic
Fixes #205 
TODO:

docker container: mount via export

---

requirements.txt

drop enum34 requirment for python3

---

conu/apidefs/container.py
conu/apidefs/image.py
conu/apidefs/metadata.py
conu/backend/docker/backend.py
conu/backend/docker/container.py
conu/backend/docker/image.py
conu/backend/nspawn/container.py
conu/backend/nspawn/image.py
tests/integration/test_docker.py
tests/integration/test_nspawn_backend.py

- get_container_metadata implemented in Docker backend
- minor change in ContainerMetadata, port_mappings is now dict {"host_port": [list_of_container_ports]}
- test is provided
We need to discuss the naming of methods here, get_metadata and get_container_metadata sounds similar what can be confusing for users.

get container metadata from docker metadata

---

Makefile
docs/source/examples/check_env.py
docs/source/examples/run_image.py
requirements.sh
tests/integration/test_docker.py
tests/unit/test_utils.py

- Id of user nobody has been changed in fedora 28: https://fedoraproject.org/wiki/Changes/RenameNobodyUser
- use whole name for images - `docker.io/fedora` was breaking this example

Fix tests and uid and gid of nobody

---

conu/backend/docker/container.py
conu/backend/docker/container_parameters.py
conu/backend/docker/image.py
tests/integration/test_docker.py

based on work done in this [PR](https://github.com/dhodovsk/conu/pull/2)
Now we can convert object of type `DockerRunBuilder` and create instance of new introduced class `DockerContainerParameters`. Properties of this class can be used for running `docker run` using [docker-py API](https://github.com/docker/docker-py).
Functionality not cover all possible parameters, but they can be implemented easily in future PRs if this changes will be merged.
I will be glad for review.

docker run parameters

---

Makefile

in order to always build conu:dev image

[Makefile] centos-ci-test depends on container-image

---

conu/utils/__init__.py
tests/integration/test_utils.py

Fixes #211 
_Old behaviour_
```
>>> from conu.utils import run_cmd
>>> ret = run_cmd(['ls'])
CHANGELOG.md	  docs			pytest.ini	   setup.cfg
CONTRIBUTING.md   examples		README.md	   setup.py
conu		  LICENSE		release-conf.yaml  test-requirements.sh
conu.spec	  Makefile		requirements.in    tests
Dockerfile	  MANIFEST.in		requirements.sh    Vagrantfile
Dockerfile.tests  pytest-container.ini	requirements.txt
>>> ret
>>> ret = run_cmd(['ls'], return_output=True)
>>> ret
'CHANGELOG.md\nCONTRIBUTING.md\nconu\nconu.spec\nDockerfile\nDockerfile.tests\ndocs\nexamples\nLICENSE\nMakefile\nMANIFEST.in\npytest-container.ini\npytest.ini\nREADME.md\nrelease-conf.yaml\nrequirements.in\nrequirements.sh\nrequirements.txt\nsetup.cfg\nsetup.py\ntest-requirements.sh\ntests\nVagrantfile\n'
```
_New behaviour_
``` …
```

Use Popen in run_cmd and pipe outputs to logger

---

Makefile
conu/utils/__init__.py
tests/integration/test_k8s.py
tests/integration/test_openshift.py

This PR contains:
1.  move tests for k8s and origin backend to classes` TestK8s` and `TestOpenshift`.
2. skip k8s and origin tests if:
-  oc command does not exist
-  OpenShift cluster is not running
3. allow using `make test-in-container` even when ~/.kube directory doesn't exist on the host (k8s and OpenShift tests will be skipped)

skip origin and k8s tests if there is no OpenShift installed or running

---

Makefile
conu/backend/docker/image.py
conu/utils/probes.py
tests/integration/test_backend.py
tests/integration/test_docker.py
tests/unit/test_probe.py

This was failing for me locally, while it's passing in CI. It's a race condition when dkr creates the file but does not populate it yet, while we already read and read `""`.
I also reordered and polished the probe code a bit. I actually don't understand why we have `.run_in_background` -- the functionality is pretty much identical to `.run` -- probes are really about blocking until a condition is met, so non-blocking seems pretty weird to me.

fix race condition when starting dkr conts via binary

---

Dockerfile.tests
Makefile
tests/integration/test_podman.py

This should fix the CI
Fixes #328
```
$ make test-in-container TEST_TARGET='-k podman'
docker run \
--rm -ti \
--net=host \
--privileged \
-e STORAGE_DRIVER=vfs \
-e CGROUP_MANAGER=cgroupfs \
--security-opt label=disable \
-v /dev:/dev:ro \
-v /var/lib/docker:/var/lib/docker:ro \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /home/tt/g/user-cont/conu:/src \
-v /home/tt/g/user-cont/conu/pytest-container.ini:/src/pytest.ini \
-v /tmp/tmp.conu-kube-Z9xN3:/root/.kube \
conu-tests make exec-test TEST_TARGET='-k podman'
cat pytest.ini
[pytest]
addopts = -vv -m "not selinux and not release_copr and not release_pypi and not nspawn"
PYTHONPATH=/src pytest-2 -k podman --verbose --showlocals
================================ test session starts =================================
platform linux2 -- …
```

run podman tests in a container

---

conu/backend/k8s/deployment.py
conu/backend/k8s/pod.py
tests/integration/test_k8s.py

- Functionality is implemented in the constructor of `Pod` class, not in `run_in_pod` method because we want to be able to create pod without `DockerBackend`.
- not sure if this is the best way how to handle metadata, but add them all as parameters or even create `PodMetadata` with all of them, seem like overkill to me.
Related to  #277.

Creation of pod from template using k8s backend

---

conu/apidefs/metadata.py
conu/backend/docker/image.py
conu/backend/k8s/pod.py
conu/backend/origin/backend.py
docs/source/new_releases.rst

Hi,
This PR is a fix for #358 .
Sphinx output:
```
make -C docs/ html
make[1]: Entering directory '/tmp/conu-fork/docs'
Running Sphinx v2.2.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
updating environment: [new config] 25 added, 0 changed, 0 removed
reading sources... [  4%] asciinema
reading sources... [  8%] examples
reading sources... [ 12%] index
reading sources... [ 16%] installation
reading sources... [ 20%] new_releases
reading sources... [ 24%] reference/api_index
reading sources... [ 28%] reference/container
reading sources... [ 32%] reference/docker_container
reading sources... [ 36%] reference/docker_image
reading sources... [ 40%] reference/docker_index
reading …
```

Fix sphinx warnings

---

Makefile

I had this problem when I am simply using make as 
```
make test-in-container TEST_TARGET=tests/integration/test_buildah.py
```
probably my first run as I don't have conu-tests locally, docker tries to pull it from remote and fails, Having build-test-container at compulsion for every test run in a container would be helpful as well as defensive in all scenarios.  This should not be a problem as docker get's things from the cache if things already exist.

build test image on every test run as part of test-in-container

---

Dockerfile.tests
Makefile
docs/source/examples/openshift/standalone-test-app/requirements.txt
files/install-openshift.yaml
files/registry_config.yml

* Enable epel for ansible
* Install the latest 3.x version of origin
* Use images from Quay for oc cluster up
* Pin dependencies for sample application
* Deploy and configure registry mirror to docker hup for docker daemon
* Use registry proxy also for podman 
The last two commits are tiny workaround for docker hub rate limit; but they are not sufficient
they just reduce impact a bit; necessary images for tests should be probably copied  to quay.io (conu namespace)

Few fixex fot execution tests in centos-ci
