user-cont/conu

conu/docker/core.py, conu/docker/selftest.py, conu/utils/core.py, conu/utils/selftest.py, examples/scl_postgres/scl_postgre.py
I didn't like how Image performs more things than it should, e.g. pulling the image by default. I was also confused by several variable/attribute names -- I think we should be as close to docker terminology as possible (check manpages). This is probably not final. I will continue tomorrow.
@jscotka Honzo, can you take a look please?
=> sanitize Image class

conu/docker/core.py
=> let's make CI green once again

.gitignore
This Pull Request add .idea project settings into .gitignore file
=> Add PyCharm into .gitignore

conu/docker/core.py, conu/docker/selftest.py
=> implement "read file" for container

conu/apidefs/__init__.py, conu/apidefs/container.py
not complete yet, comments are welcome
=> incept container API definition

.travis.yml, conu/__init__.py, conu/apidefs/__init__.py, conu/apidefs/backend.py, conu/apidefs/container.py, conu/apidefs/image.py, conu/backend/docker/__init__.py, conu/backend/docker/backend.py, conu/backend/docker/container.py, conu/backend/docker/image.py, conu/docker/__init__.py, conu/docker/core.py, conu/utils/__init__.py, requirements.txt, test-requirements.txt, tests/integration/test_docker.py
=> implement http client for container, incept backend interface

.travis.yml, conu/apidefs/container.py, conu/apidefs/image.py, conu/backend/docker/__init__.py, conu/backend/docker/container.py, conu/backend/docker/image.py, examples/scl_postgres/scl_postgre.py, tests/integration/conftest.py, tests/integration/constants.py, tests/integration/test_docker.py, tests/unit/test_docker_container.py
=> Sanitize docker implementation

conu/backend/docker/client.py, conu/backend/docker/container.py, conu/backend/docker/image.py, requirements.txt, test-requirements.txt
=> use docker-py

.travis.yml, Makefile, conu/apidefs/container.py, conu/apidefs/filesystem.py, conu/apidefs/image.py, conu/backend/docker/container.py, conu/backend/docker/image.py, requirements.txt, tests/integration/test_docker.py, tests/integration/test_filesystem.py
I rebased and working on fixing tests.
=> add and implement filesystem interface

Makefile, requirements.sh
=> Add script to install dependencies

conu/backend/docker/container.py, conu/utils/core.py, conu/utils/probes.py, examples/scl_postgres/scl_postgre.py, tests/integration/test_utils.py, tests/unit/test_probe.py
This PR introduces probe with features:
- will run only for specified amount of time
- ignores expected exceptions
- accepts  outputs other than True
=> Re-implement probe

Dockerfile.tests, Makefile, conu/apidefs/container.py, conu/apidefs/image.py, conu/backend/docker/container.py, conu/backend/docker/image.py, conu/utils/core.py, requirements.sh, tests/integration/__init__.py, tests/integration/conftest.py, tests/integration/constants.py, tests/integration/data/punchbag/.s2i/bin/assemble, tests/integration/data/punchbag/.s2i/bin/run, tests/integration/data/punchbag/.s2i/bin/usage, tests/integration/data/punchbag/Dockerfile, tests/integration/test_s2i.py
You may hit this:
https://bugzilla.redhat.com/show_bug.cgi?id=1510476
This PR also contains:
* add wait() method for containers
* set up logging for tests
=> implement s2i testing

Makefile, conu/utils/filesystem.py, tests/integration/test_utils.py, tests/unit/test_utils.py
Fixes: https://github.com/fedora-modularity/meta-test-family/issues/92
=> utils/Directory: add a way to set uid/gid

conu/apidefs/container.py, conu/apidefs/filesystem.py, conu/apidefs/image.py, conu/backend/docker/container.py, conu/utils/__init__.py, conu/utils/filesystem.py, tests/integration/test_docker.py, tests/integration/test_filesystem.py
* reintroduce copy_to 'n stuff
* utils/check_port: remove default from "host"
* documentation updates
=> changes based on collaborative review

conu/apidefs/container.py, conu/backend/docker/container.py, conu/utils/__init__.py, conu/utils/filesystem.py, docs/source/examples/webserver.py
* introduce a func to detect if selinux is disabled
* implement kill for docker containers
* docs updates
=> more fixes based on collaborative review

conu/apidefs/container.py, conu/backend/docker/container.py, tests/integration/test_docker.py
Fixes https://github.com/fedora-modularity/conu/issues/79
=> Add exit code method

conu/backend/docker/container.py, tests/integration/test_docker.py
=> raise an exc when container creation fails

README.md, conu/apidefs/container.py, conu/apidefs/image.py, conu/backend/docker/container.py, conu/backend/docker/image.py, docs/source/examples.rst, docs/source/examples/check_port.py, docs/source/examples/run_image.py, docs/source/examples/s2i.py, docs/source/examples/webserver.py, docs/source/reference/docker_container.rst, docs/source/reference/docker_image.rst, tests/integration/test_docker.py, tests/integration/test_filesystem.py, tests/integration/test_s2i.py, tests/unit/test_docker_container.py
fixes: https://github.com/fedora-modularity/conu/issues/11
=> relocate run methods from container to image

.tito/packages/.readme, .tito/tito.props, README.md, conu.spec, conu/apidefs/image.py, conu/backend/docker/image.py, conu/version.py, docs/source/examples/readme_webserver.py, docs/source/examples/webserver.py, examples
This branch is present in upstream repo: feel free to add commits to it, or even rebase it.
=> 0.1.0 release

.travis.yml, Makefile, pytest-container.ini, pytest.ini, tests/release/test_release.py
=> add tests for a release

conu/apidefs/backend.py, conu/backend/docker/container.py, tests/integration/test_docker.py
There still more room for improvements. The current implementation is heavily influenced by docker.
TODO:
=> better execute

conu/apidefs/container.py, conu/backend/docker/container.py, conu/backend/docker/image.py, docs/source/reference/docker_container.rst, docs/source/reference/docker_image.rst, tests/integration/test_docker.py, tests/integration/test_s2i.py
Fixes #88
~~Blocked by https://github.com/sphinx-doc/sphinx/issues/4479.~~
TODO:
=> better docs for logs()

README.md, conu/apidefs/backend.py, conu/backend/docker/backend.py, docs/source/examples/check_env.py, docs/source/examples/check_port.py, docs/source/examples/client-server-request.py, docs/source/examples/readme_webserver.py, docs/source/examples/run_image.py, docs/source/examples/s2i.py, docs/source/examples/webserver.py, docs/source/reference/api_index.rst, docs/source/reference/docker_index.rst, tests/integration/test_backend.py, tests/integration/test_docker.py, tests/integration/test_filesystem.py
=> backend as a context manager

conu/backend/docker/container.py, docs/source/examples/check_env.py, docs/source/examples/client-server-request.py, tests/integration/test_docker.py, tests/integration/test_s2i.py
Fixes https://github.com/fedora-modularity/conu/issues/123
=> Provide convenience methods for logs

conu/backend/docker/client.py, conu/backend/docker/container.py, conu/backend/docker/image.py, conu/utils/__init__.py, conu/utils/filesystem.py, tests/integration/test_utils.py, tests/release/test_release.py
=> check if binaries are present

conu.spec, conu/__init__.py, conu/backend/docker/image.py, conu/utils/__init__.py, docs/source/conf.py, docs/source/examples/check_port.py, docs/source/examples/client-server-request.py, docs/source/examples/readme_webserver.py, docs/source/examples/run_image.py, docs/source/examples/s2i.py, docs/source/examples/webserver.py, docs/source/reference/docker_image.rst, requirements.sh, requirements.txt, tests/integration/test_docker.py, tests/unit/test_utils.py
TODO:
I'm open to all the comments.
=> introduce pull policy to docker images

README.md, conu/backend/docker/image.py, conu/exceptions.py, conu/utils/rpms.py, docs/source/examples/check_signature.py
Mostly copy and paste from code written by lzachar.
Additional requested functionality not covered in this PR:
- auto detection of allowed keys
- print origin (repository) of not properly signed packages in logs
=> Add possibility to check signature

conu/utils/__init__.py
Resolves #118 
Do I need to fix also other log messages?
=> Correct form of docker run command in log

Dockerfile.tests
=> don't create pyc files in test container

conu.spec
There were some changes that I missed with #147, I didn't notice they were merged to master branch in pagure. This PR fixes that.
=> Update spec file with latest version

conu/apidefs/container.py, conu/utils/http_client.py, tests/integration/test_docker.py, tests/unit/test_utils.py
Resolves #25 
- Is the `HttpClient` class in a good location?
- Is the naming/style ok?
=> Http context

Dockerfile, Dockerfile.tests
=> don't create .pyc files in conu container

Makefile, conu.spec, conu/backend/docker/image.py, conu/fixtures/__init__.py, conu/helpers/__init__.py, conu/helpers/docker_backend.py, docs/source/examples.rst, docs/source/examples/client-server-request.py, docs/source/index.rst, docs/source/reference/fixtures_index.rst, docs/source/reference/helpers_index.rst, docs/source/reference/index.rst, requirements.txt, tests/integration/test_backend.py, tests/integration/test_helpers.py
=> introduce fixtures and helper functions

README.md
=> Add usage for containerized conu

conu/backend/docker/image.py, conu/utils/filesystem.py, docs/source/examples/webserver.py, tests/integration/test_docker.py, tests/unit/test_utils.py
Resolves #81 
What do you think about this approach?
=> Directory instance in run

README.md
Fix #107 
Add links to container images that already using `conu`
This is still work-in-progress, feel free to comment or send PR with links to another projects that you are aware of.
=> [WIP] real examples linked from README.md

conu/apidefs/backend.py, conu/backend/docker/backend.py, tests/integration/test_backend.py
See #116.
I will be glad for the review.
=> docker backend cleanup containers on exit

conu/apidefs/container.py, conu/backend/docker/container.py
Resolves #167 
I don't like this approach too much, but it works. I guess that some tests for that will be necessary.
=> Be able to create a container without specifying image

README.md
FIXES #165
1. I replace the old name `./example.py` with the new one `examples/readme_webserver.py`.
2. I updated the code, but the output is still the same.
=> README.md updated with new script

.gitignore
- ignore PyCharm files
- minor cleanup
=> minor update of .gitignore

Makefile
@enriquetaso this should help you
=> make: $(CURDIR) is better than ${PWD}

Makefile, Vagrantfile, conu/backend/nspawn/__init__.py, conu/backend/nspawn/backend.py, conu/backend/nspawn/constants.py, conu/backend/nspawn/container.py, conu/backend/nspawn/image.py, conu/utils/__init__.py, tests/integration/test_nspawn_backend.py
It is ready to review&merge
all major issues based on review fixed.
documentation added
able to run tests via vagrant:
```
make test-nspawn-vagrant
```
all suggestions and future RFEs mentioned in code with ``TODO`` comment
=> systemd-nspawn container support

setup.cfg
=> Add config for PyPI to see description on the PyPI web

conu/apidefs/backend.py, conu/backend/docker/backend.py, conu/backend/docker/image.py, conu/backend/nspawn/backend.py, conu/backend/nspawn/container.py, conu/backend/nspawn/image.py, pytest-container.ini, test-requirements.txt, tests/integration/test_docker.py, tests/integration/test_nspawn_backend.py
=> add list_{container,image} to the API

conu/backend/nspawn/backend.py, conu/backend/nspawn/container.py, conu/backend/nspawn/image.py, tests/integration/test_nspawn_backend.py
Please don't look yet. Let's merge #180 first, then I rebase, then we can figure out what we want to do.
=> WIP WIP nspawn madness WIP WIP

conu/apidefs/backend.py, conu/backend/docker/backend.py, conu/backend/docker/container.py, conu/backend/docker/image.py, conu/backend/nspawn/backend.py, tests/integration/test_docker.py
commits:
* add name property to backend
* list-images: enable passing the metadata
=> improve list-images, add name prop to backend

conu/__init__.py, conu/apidefs/filesystem.py, conu/backend/docker/image.py, docs/source/reference/docker_image.rst, tests/integration/test_filesystem.py
Franto, no code changes are needed in colin I believe.
Also, I couldn't run the tests because of https://bugzilla.redhat.com/show_bug.cgi?id=1570828
=> docker_image.mount() via .get_archive()

CHANGELOG.md
Please let me know if there is something forgotten in the changelog
=> 0.3.0 release

conu/backend/docker/image.py, tests/integration/test_docker.py
Fixes https://github.com/user-cont/conu/issues/65
=> Methods for getting image layers

CONTRIBUTING.md
See #190 
- Structure copied from [colin](https://github.com/user-cont/colin) repository, see [CONTRIBUTING.md](https://github.com/user-cont/colin/blob/master/CONTRIBUTING.md)
- added some more points, describing Pull Request workflow
=> First shot at CONTRIBUTING.md

conu/__init__.py, conu/backend/docker/image.py
Also added a shortcut for cleanup policy enum
=> Add recently added parameters also to s2i image class

.gitignore, CHANGELOG.md, Makefile, conu.spec, conu/backend/docker/container.py, conu/version.py, docs/source/reference/docker_container.rst, docs/source/reference/filesystem_api.rst
=> 0.4.0 release

conu/apidefs/image.py, conu/apidefs/metadata.py, conu/backend/docker/image.py, tests/integration/test_docker.py
=> get_metadata for DockerImage

.bandit, .pylintrc
- Use bandit/pylintrc file from kwaciaren.
-----
Please, do not change .bandit/.pylintrc files here, but first in [our config repo](https://github.com/user-cont/kwaciaren) so we can share common configuration between all projects.
(Kwaciaren, the config repo, has scripts for sharing such files.)
=> Use config from user-cont/kwaciaren

conu/fixtures/__init__.py, requirements.txt
It's in [tests/requirements.txt](https://github.com/user-cont/conu/blob/master/tests/requirements.txt) and therefore installed in [Dockerfile.tests](https://github.com/user-cont/conu/blob/master/Dockerfile.tests).
If there's a reason for having it in main requirements, I'd like to hear about it, so I can add some comments instead of removing it.
=> Comment pytest requirement

conu/apidefs/metadata.py, conu/backend/docker/backend.py, conu/backend/docker/container.py, conu/backend/docker/image.py, conu/backend/docker/utils.py, conu/utils/__init__.py, tests/constants.py, tests/integration/__init__.py, tests/integration/conftest.py, tests/integration/test_docker.py
@rpitonak would you take a look when you get back?
=> docker digests as alternative names

Makefile, test-requirements.sh, tests/integration/test_k8s.py
Minikube for centos-ci. Fixes #241
=> Minikube for CI

conu/backend/docker/image.py
=> [DockerImage:pull()] decode JSON data into dicts

Makefile, conu/apidefs/backend.py, conu/backend/k8s/backend.py, tests/integration/test_k8s.py
=> k8s cleanup policy enum and cleanup methods

setup.py
=> Adjust setup.py to work properly with Kebechet

requirements.sh
=> install gcc, python-devel in the image

tests/integration/test_backend.py
=> pytest.mark.xfail test_cleanup_containers()

README.md, conu/backend/docker/backend.py, conu/backend/docker/image.py, conu/backend/k8s/backend.py, conu/backend/k8s/client.py, conu/backend/k8s/service.py, conu/backend/origin/__init__.py, conu/backend/origin/backend.py, conu/backend/origin/constants.py, conu/utils/__init__.py, docs/source/examples/openshift/openshift_s2i_local.py, docs/source/examples/openshift/openshift_s2i_remote.py, docs/source/examples/openshift/openshift_template.py, docs/source/examples/openshift/standalone-test-app/app.py, docs/source/examples/openshift/standalone-test-app/requirements.txt, requirements.txt, tests/integration/test_openshift.py
- Openshift backend
- 'oc new-app'
- examples
Openshift tests are skipped temporary because of CI.
I would like to hear feedback for naming, design etc. - that's why it is still WIP.
=> OpenShift origin backend

release-conf.yaml
see https://github.com/user-cont/release-bot/pull/76
=> Allow release-bot to make PRs based on issues

conu/backend/k8s/pod.py, docs/source/examples/k8s_pod.py, tests/integration/test_k8s.py
- new `PodCondition` enum
- Implemented `is_ready() function`
- `wait()` now wait until pod is in `READY` condition instead of `RUNNING` phase
- 'get_logs()' implemented
- new pod example
=> K8s pod improvements

conu/apidefs/filesystem.py, requirements.in, requirements.sh, tests/integration/test_filesystem.py
=> remove pyxattr, make it optional

CONTRIBUTING.md, Dockerfile.docs, Makefile, README.md, conu/apidefs/metadata.py, conu/backend/docker/image.py, conu/backend/k8s/backend.py, conu/backend/k8s/deployment.py, conu/backend/k8s/pod.py, conu/backend/k8s/service.py, docs/source/conf.py, docs/source/examples.rst, docs/source/examples/k8s_deployment.py, docs/source/examples/k8s_pod.py, docs/source/examples/openshift/openshift_s2i_local.py, docs/source/examples/openshift/openshift_s2i_remote.py, docs/source/examples/openshift/openshift_template.py, docs/source/index.rst, docs/source/installation.rst, docs/source/new_releases.rst, docs/source/reference/index.rst, docs/source/reference/k8s_deployment.rst, docs/source/reference/k8s_index.rst, docs/source/reference/k8s_pod.rst, docs/source/reference/k8s_service.rst, docs/source/reference/origin_index.rst, setup.py
Once our documentation is working again thanks to #282, I have decided to make an update to it.
It is quite a lot changes, I am suggesting to build it locally and go through all pages during the review.
Other than that, README.md and CONTRIBUTING.md (fix #256 and #190) were also updated.
There are probably still things that I didn't notice or wrote in a wrong way, so suggestions are very welcome.
=> Docs update

Dockerfile.tests, requirements.sh
related https://github.com/user-cont/conu/pull/290
=> req.sh: clarify deps, remove make; remove pytest from dfile.tests

Vagrantfile, conu/backend/nspawn/backend.py, conu/backend/nspawn/constants.py, conu/backend/nspawn/container.py, conu/backend/nspawn/image.py, tests/integration/test_nspawn_backend.py
there were several changes what caused troubles
* another test image location
* do not use pull-raw and importing via machinectl, because nobody uses it and causes troubles,
after dicsussion with systemd devels it is better to do it in own way
* imrpove tesing of output added chars decode from stdout
verified locally with pytest-3:
```
$ sudo pytest-3 -x tests/integration/test_nspawn_backend.py 
================================================================== test session starts ===================================================================
platform linux -- Python 3.6.6, pytest-3.4.2, py-1.5.4, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jscotka/git/conu, inifile: pytest.ini
collected 8 items …
```
=> make nspawn backend already working

Makefile
=> remove git clean and encrypt password for Travis CI

requirements.sh
this is needed when invoking tests in vagrant
=> req.sh: add nmap-ncat

test-requirements.sh
=> add podman to test-requirements

requirements.in, requirements.txt, setup.py
And let's ship this after it's merged!
Fixes #314
Fixes #313
=> Packaging is fun

MANIFEST.in, conu.spec
* spec: change dep on sphinx to python3-sphinx package
* include requirements.in in release tarball
=> Fix RPM packaging

conu/backend/origin/backend.py, tests/integration/test_openshift.py
Make a project parameter optional in deployment methods.
=> New method in origin backend: get_current_project.

test-requirements.sh
=> download newer version of oc cluster in test-requirements.sh

conu/backend/k8s/deployment.py
https://nvd.nist.gov/vuln/detail/CVE-2017-18342
=> [backend/k8s/deployment.py] yaml.load() -> yaml.safe_load()

Makefile, conu.spec
=> sync spec from Fedora

release-conf.yaml
https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/message/VNCIQRESRZX3Q74WL5TLZCQW7LHLTGQM/
=> [release-conf.yaml] F30 has been branched

conu/backend/docker/image.py, conu/backend/docker/skopeo.py, requirements.sh, test-requirements.sh, tests/integration/test_docker.py, tests/requirements.txt
=> WIP DockerImage.copy

Dockerfile.tests, Makefile, conu/backend/buildah/__init__.py, conu/backend/buildah/backend.py, conu/backend/buildah/constants.py, conu/backend/buildah/container.py, conu/backend/buildah/image.py, conu/backend/buildah/utils.py, conu/backend/docker/backend.py, conu/backend/podman/backend.py, conu/backend/podman/container.py, conu/backend/podman/image.py, conu/backend/podman/utils.py, conu/exceptions.py, conu/fixtures/__init__.py, conu/utils/__init__.py, conu/utils/probes.py, files/install-packages.yaml, pytest.ini, tests/integration/test_buildah.py, tests/integration/test_docker.py, tests/integration/test_podman.py
=> add buildah backend

.github/workflows/pypi-publish.yml
=> Github action/workflow to upload release to PyPI
